# Script à utiliser avec le fichier ecrit par la fonction PrintDataPowerIt dans EdgeList.cpp

import matplotlib.pyplot as plt
import numpy as np

# ouverture et lecture du fichier
f= open("D:\\Graphes_RDM\\Res_PageRank_Final.txt","r")
print("tic")
L=f.readline().split(" ")
L.pop(-1) # Pb car il y a un espace en fin de ligne
P=[float(t) for t in L]
print("tic")
L=f.readline().split(" ")
L.pop(-1)
P1=[float(t) for t in L]
print("tic")
L=f.readline().split(" ")
L.pop(-1)
P2=[float(t) for t in L]
print("tic")
L=f.readline().split(" ")
L.pop(-1)
P5=[float(t) for t in L]
print("tic")
L=f.readline().split(" ")
L.pop(-1)
P9=[float(t) for t in L]
print("tic")
L=f.readline().split(" ")
L.pop(-1)
InDegree=[int(t) for t in L]
print("tic")
L=f.readline().split(" ")
L.pop(-1)
OutDegree=[int(t) for t in L]
print("tac !")

# fig,ax=plt.subplot(1)
plt.scatter(np.log(P),np.log(InDegree))
plt.title("In degree")
plt.xlabel("PageRank")
plt.ylabel("In degree")
# plt.yscale('log')
# plt.xscale('log')
# plt.show()
print("saving")
plt.savefig("InDeg_Fin.png")
plt.close()

plt.scatter(np.log(P),np.log(OutDegree))
plt.title("Out degree")
plt.xlabel("PageRank")
plt.ylabel("Out degree")
# plt.yscale('log')
# plt.xscale('log')
# plt.show()
print("saving")
plt.savefig("OutDeg_Fin.png")
plt.close()

plt.scatter(P,P1)
plt.title("PageRank 0.1")
plt.xlabel("PageRank 0.15")
plt.ylabel("PageRank 0.1")
plt.yscale('log')
plt.xscale('log')
# plt.show()
print("saving")
plt.savefig("PR1_Fin.png")
plt.close()

plt.scatter(P,P2)
plt.title("PageRank 0.2")
plt.xlabel("PageRank 0.15")
plt.ylabel("PageRank 0.2")
plt.yscale('log')
plt.xscale('log')
# plt.show()
print("saving")
plt.savefig("PR2_Fin.png")
plt.close()

plt.scatter(P,P5)
plt.title("PageRank 0.5")
plt.xlabel("PageRank 0.15")
plt.ylabel("PageRank 0.5")
plt.yscale('log')
plt.xscale('log')
# plt.show()
print("saving")
plt.savefig("PR5_Fin.png")
plt.close()

plt.scatter(P,P9)
plt.title("PageRank 0.9")
plt.xlabel("PageRank 0.15")
plt.ylabel("PageRank 0.9")
plt.yscale('log')
plt.xscale('log')
# plt.show()
print("saving")
plt.savefig("PR9_Fin.png")
plt.close()

plt.scatter(np.log(InDegree),np.log(OutDegree))
plt.title("corrélation in/out degree")
plt.xlabel("In Degree")
plt.ylabel("Out Degree")
# plt.yscale('log')
# plt.xscale('log')
# plt.show()
print("saving")
plt.savefig("InOutDegreeLog.png")
plt.close()